"""
Constants and enums for the ARC investment platform.

This module defines all domain-specific enumerated types used throughout
the codebase for type-safe value constraints, database validation, and
API request/response validation.

All enums use StrEnum for JSON serialization compatibility.
"""

from enum import StrEnum


class PortfolioType(StrEnum):
    """Types of portfolios in the ARC platform."""

    MANAGED = "managed"  # Actively managed portfolios
    MODEL = "model"  # Model/strategy portfolios
    BENCHMARK = "benchmark"  # Benchmark portfolios for comparison
    COMPOSITE = "composite"  # Composite of multiple portfolios


class TransactionType(StrEnum):
    """Types of portfolio transactions."""

    BUY = "buy"
    SELL = "sell"
    DIVIDEND = "dividend"
    INTEREST = "interest"
    TRANSFER_IN = "transfer_in"
    TRANSFER_OUT = "transfer_out"
    FEE = "fee"
    SPLIT = "split"
    MERGER = "merger"
    SPINOFF = "spinoff"
    RIGHTS_ISSUE = "rights_issue"


class AlertSeverity(StrEnum):
    """Severity levels for alerts and notifications."""

    INFO = "info"  # Informational, no action required
    WARNING = "warning"  # Requires attention
    CRITICAL = "critical"  # Immediate action required


class AlertType(StrEnum):
    """Types of alerts generated by the system."""

    PRICE_MOVEMENT = "price_movement"
    VOLUME_SPIKE = "volume_spike"
    RATIO_THRESHOLD = "ratio_threshold"
    COMPLIANCE_BREACH = "compliance_breach"
    PORTFOLIO_DRIFT = "portfolio_drift"
    REBALANCE_NEEDED = "rebalance_needed"
    EARNINGS_ANNOUNCEMENT = "earnings_announcement"
    DIVIDEND_DECLARED = "dividend_declared"
    NEWS_ALERT = "news_alert"
    CUSTOM = "custom"


class RatioClass(StrEnum):
    """Classifications for financial ratios."""

    LIQUIDITY = "liquidity"  # Current ratio, quick ratio
    PROFITABILITY = "profitability"  # ROE, ROA, margins
    LEVERAGE = "leverage"  # Debt ratios
    EFFICIENCY = "efficiency"  # Asset turnover, inventory turnover
    VALUATION = "valuation"  # P/E, P/B, EV/EBITDA
    GROWTH = "growth"  # Revenue growth, earnings growth


class UserRole(StrEnum):
    """User roles and permission levels."""

    ADMIN = "admin"  # Full system access
    INVESTMENT_MANAGER = "investment_manager"  # Portfolio management
    FAMILY_OFFICE = "family_office"  # Client-level access
    COMPLIANCE = "compliance"  # Compliance and audit
    ANALYST = "analyst"  # Research and analysis
    VIEWER = "viewer"  # Read-only access


class AssetClass(StrEnum):
    """Asset class categorization."""

    EQUITY = "equity"
    FIXED_INCOME = "fixed_income"
    CASH = "cash"
    REAL_ESTATE = "real_estate"
    COMMODITIES = "commodities"
    ALTERNATIVES = "alternatives"
    CRYPTO = "crypto"
    PRIVATE_EQUITY = "private_equity"
    HEDGE_FUND = "hedge_fund"


class SecurityType(StrEnum):
    """Types of securities."""

    STOCK = "stock"  # Common stock
    PREFERRED = "preferred"  # Preferred stock
    ETF = "etf"  # Exchange-traded fund
    MUTUAL_FUND = "mutual_fund"  # Mutual fund
    BOND = "bond"  # Bond/fixed income
    OPTION = "option"  # Option contract
    FUTURE = "future"  # Futures contract
    REIT = "reit"  # Real estate investment trust
    ADR = "adr"  # American depositary receipt
    WARRANT = "warrant"  # Stock warrant
    RIGHT = "right"  # Subscription right


class MarketStatus(StrEnum):
    """Market trading status."""

    OPEN = "open"
    CLOSED = "closed"
    PRE_MARKET = "pre_market"
    AFTER_HOURS = "after_hours"
    HALTED = "halted"


class DataProvider(StrEnum):
    """External data provider sources."""

    EODHD = "eodhd"  # EODHD market data
    CAPITAL_IQ = "capital_iq"  # S&P Capital IQ
    PITCHBOOK = "pitchbook"  # Pitchbook private markets
    MANUAL = "manual"  # Manually entered data
    INTERNAL = "internal"  # Internal calculations


class SyncStatus(StrEnum):
    """Data synchronization status."""

    PENDING = "pending"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    FAILED = "failed"
    CANCELLED = "cancelled"


class Currency(StrEnum):
    """Supported currencies."""

    USD = "USD"
    EUR = "EUR"
    GBP = "GBP"
    JPY = "JPY"
    CHF = "CHF"
    CAD = "CAD"
    AUD = "AUD"
    HKD = "HKD"
    SGD = "SGD"
    CNY = "CNY"
    NZD = "NZD"
    SEK = "SEK"
    NOK = "NOK"
    DKK = "DKK"


class TimeHorizon(StrEnum):
    """Investment time horizons for performance calculation."""

    INTRADAY = "intraday"
    DAILY = "daily"
    WEEKLY = "weekly"
    MONTHLY = "monthly"
    QUARTERLY = "quarterly"
    YEARLY = "yearly"
    YTD = "ytd"  # Year-to-date
    MTD = "mtd"  # Month-to-date
    QTD = "qtd"  # Quarter-to-date


class ReportType(StrEnum):
    """Types of reports generated."""

    PERFORMANCE = "performance"
    HOLDINGS = "holdings"
    TRANSACTIONS = "transactions"
    ATTRIBUTION = "attribution"
    RISK = "risk"
    COMPLIANCE = "compliance"
    TAX = "tax"
    CUSTOM = "custom"


class OrderStatus(StrEnum):
    """Trading order status."""

    PENDING = "pending"
    SUBMITTED = "submitted"
    PARTIALLY_FILLED = "partially_filled"
    FILLED = "filled"
    CANCELLED = "cancelled"
    REJECTED = "rejected"
    EXPIRED = "expired"


class OrderType(StrEnum):
    """Trading order types."""

    MARKET = "market"
    LIMIT = "limit"
    STOP = "stop"
    STOP_LIMIT = "stop_limit"
    TRAILING_STOP = "trailing_stop"


# =============================================================================
# CONSTANTS
# =============================================================================

# API Pagination
DEFAULT_PAGE_SIZE = 20
MAX_PAGE_SIZE = 100

# Cache TTL (seconds)
CACHE_TTL_SHORT = 60  # 1 minute
CACHE_TTL_MEDIUM = 300  # 5 minutes
CACHE_TTL_LONG = 3600  # 1 hour
CACHE_TTL_MARKET_DATA = 900  # 15 minutes (market data)

# Rate Limits
RATE_LIMIT_DEFAULT = 100  # requests per minute
RATE_LIMIT_HEAVY = 10  # requests per minute for heavy operations

# Date Formats
DATE_FORMAT = "%Y-%m-%d"
DATETIME_FORMAT = "%Y-%m-%dT%H:%M:%SZ"
DATETIME_FORMAT_MS = "%Y-%m-%dT%H:%M:%S.%fZ"

# Financial Constants
TRADING_DAYS_PER_YEAR = 252
BASIS_POINTS_DIVISOR = 10000  # 100 basis points = 1%

# Risk-free rate assumptions (for calculations)
DEFAULT_RISK_FREE_RATE = 0.05  # 5% annual

# Default currency
DEFAULT_CURRENCY = Currency.USD
